version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "angular-build-deployment"
        BUILD_FOLDER: "dist"
APP_NAME: "angular-app"
BUILD_ENV : "prod"

phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started on `date`
        - ng build --${BUILD_ENV}

  post_build:
        commands:
        # Copy dist folder to S3 bucket
        - aws s3 cp dist s3://${S3_BUCKET}/${APP_NAME} --recursive
        - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes